import Head from 'next/head'
import HomeAccordian from '../components/HomeAccordian'
// import Counter from '../features/Counter'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Redux Practice App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <div>
          <HomeAccordian />
        </div>
      </main>
    </div>
  )
}
